version: '3'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking
      - MYSQL_USER=dhia
      - MYSQL_PASSWORD=root
    ports:
      - 3308:3306

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: app:latest
    ports:
       - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/booking
   